# Generated by Django 4.1.4 on 2022-12-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count_save',
            field=models.PositiveIntegerField(default=0, verbose_name='Count Save'),
        ),
    ]
