# Generated by Django 4.1.4 on 2022-12-31 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_count_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='count_save',
        ),
    ]
