# Generated by Django 4.1.4 on 2023-01-13 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_count_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file',
            new_name='img',
        ),
    ]
