# Generated by Django 4.1.4 on 2022-12-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ImageField(default=None, upload_to='article/', verbose_name='Cover Post'),
            preserve_default=False,
        ),
    ]
