# Generated by Django 4.1.4 on 2022-12-31 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_favorites_list_user_save_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count_save',
            field=models.PositiveIntegerField(default=0, verbose_name='Count Save'),
        ),
    ]
